# Generated by Django 5.0.6 on 2025-12-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('background_color', models.CharField(default='#eeeeee', max_length=20)),
                ('text_color', models.CharField(default='#333333', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('property_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
