# Generated by Django 5.0.6 on 2025-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_property_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, help_text='Street address or area name', max_length=255),
        ),
    ]
