# Generated by Django 5.0.6 on 2025-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_occupancy',
            field=models.IntegerField(blank=True, help_text='Maximum number of people this property can accommodate', null=True),
        ),
    ]
