# Generated by Django 5.0.6 on 2026-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_shorttermlodge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorttermlodge',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='shorttermlodge',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City or area, e.g. Harare, Bulawayo, Victoria Falls', max_length=200),
        ),
        migrations.AlterField(
            model_name='shorttermlodge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
