# Generated by Django 5.0.6 on 2026-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_shorttermlodge_options_shorttermlodge_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermlodge',
            name='url',
            field=models.CharField(help_text='Full URL to the lodge website or Google Maps link', max_length=2000),
        ),
    ]
