# Generated by Django 5.0.6 on 2025-12-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_contactview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentconfirmation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
