# Generated by Django 6.0 on 2026-04-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
        ('core', '0002_feedback'),
    ]

    operations = [
    ]
