# Generated by Django 5.0.6 on 2026-04-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_contactmessage_0002_feedback'),
    ]

    operations = [
    ]
