# Generated by Django 5.0.6 on 2026-04-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_contactmessage_0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='access_anytime',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='better_decisions',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='continue_using',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='current_methods',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='improves_transparency',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='info_accurate',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='map_helps',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='meets_needs',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='prefer_over_traditional',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reasonable_internet',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='reduces_time',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfied',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='spatial_search',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='trustworthy',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='up_to_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='view_distance',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='visualization_clear',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='works_on_device',
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ui_review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ux_review',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='has_internet',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='occupation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
